name: CI
on: [push, pull_request]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq libfreetype6-dev libgif-dev libpng-dev libavutil-dev libavcodec-dev
      - name: build the application
        run: |
          make -B render
          file output.mpeg
        env:
          CXX: g++

  build-linux-clang:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq libfreetype6-dev libgif-dev libpng-dev libavutil-dev libavcodec-dev
      - name: build the application
        run: |
          make -B render
          file output.mpeg
        env:
          CC: clang
# TODO: no MacOS build
# TODO: no Windows build
